name: gepco_units_record
description: GEPCO Units Record App

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1

flutter:
  uses-material-design: true
